### ISSUE TITLE
Date container overflowed 

### ISSUE THREAD

**Issue by fareezMaple** [fareezMaple/App-Waktu-Solat-Malaysia#22]
![received_820864042058895.jpeg](https://user-images.githubusercontent.com/60868965/97001720-6f6c8900-156b-11eb-93cb-b2864f42e8f9.jpeg)
Thank you Razin for reporting.

**Comment by tajjacob** [comment]
Wrap with autosizetext widget should be fine.

**Comment by fareezMaple** [comment]
@tajjacob Noted

**Comment by fareezMaple** [comment]
Fixed on latest release
